name: BuildNNCP

on: push

jobs:
  generate_version_number:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ github.ref == 'refs/heads/master' && steps.buildnumber.outputs.build_number || 1 }}
    steps:
      - name: Generate build number
        if: github.ref == 'refs/heads/master'
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}

  build_linux:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
      - name: Download NNCP source
        run: wget https://bellard.org/nncp/nncp-2023-10-21.tar.gz -O nncp.tar
      - name: Extract NNCP source
        run: tar xf nncp.tar
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential zlib1g-dev
      - name: Build
        run: make -C nncp-2023-10-21
      - uses: actions/upload-artifact@v4
        with:
          name: nncp-linux-to-linux
          path: nncp-2023-10-21/nncp

  build_windows_on_windows:
    needs: generate_version_number
    runs-on: windows-latest
    steps:
      - name: Download NNCP source
        run: Invoke-WebRequest -Uri https://bellard.org/nncp/nncp-2023-10-21.tar.gz -OutFile nncp.tar
        shell: powershell
      - name: Extract NNCP source
        run: tar xf nncp.tar
        shell: bash
      - name: Setup MinGW-w64
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-zlib
          path-type: inherit
      - name: Build with CONFIG_WIN32
        run: |
          echo "CONFIG_WIN32=y" > config.mak
          make -C nncp-2023-10-21
        shell: msys2 {0}
      - uses: actions/upload-artifact@v4
        with:
          name: nncp-windows-to-windows
          path: nncp-2023-10-21/nncp.exe

  build_windows_on_linux:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends mingw-w64 \
          make \
          gcc \
          g++ \
          wget \
          tar \
          xz-utils \
          unzip
      
      - name: Install zlib
        run: wget http://www.zlib.net/zlib-1.3.1.tar.gz -O zlib.tar.gz && \
          tar -xf zlib.tar.gz && \
          cd zlib-1.3.1 && \
          CROSS_PREFIX=x86_64-w64-mingw32- ./configure --static --prefix=/usr/x86_64-w64-mingw32 && \
          make && \
          make install && \
          cd .. && \
          rm zlib.tar.gz

      - name: Download NNCP source + extract
        run: |
          wget https://bellard.org/nncp/nncp-2023-10-21.tar.gz -O nncp.tar
          tar xf nncp.tar
          rm nncp.tar

      - name: Download NNCP Windows Dependencies and move to source
        run: |
          wget https://bellard.org/nncp/nncp-2023-10-21-win64.zip --no-check-certificate -O nncp-win64.zip && \
          unzip nncp-win64.zip -d nncp-win64 && \
          cp nncp-win64/*.dll /usr/src/app/nncp-2023-10-21/ && \
          rm -rf nncp-win64 nncp-win64.zip

      - name: Build Windows executable on Linux
        run: |
          cd nncp-2023-10-21
          make CONFIG_WIN32=y CC=x86_64-w64-mingw32-gcc

      - uses: actions/upload-artifact@v4
        with:
          name: nncp-linux-to-windows
          path: nncp-2023-10-21/

  release_github:
    needs: [
      generate_version_number,
      build_windows_on_windows,
      build_linux,
      build_windows_on_linux,
    ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.${{needs.generate_version_number.outputs.build_number}}
          release_name: Release 1.0.${{needs.generate_version_number.outputs.build_number}}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/nncp-linux-to-linux
            ./artifacts/nncp-windows-to-windows
            ./artifacts/nncp-linux-to-windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
