name: BuildNNCP

on: push

jobs:
  generate_version_number:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ github.ref == 'refs/heads/master' && steps.buildnumber.outputs.build_number || 1 }}
    steps:
      - name: Generate build number
        if: github.ref == 'refs/heads/master'
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}

  build_linux:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
      - name: Download NNCP source
        run: wget https://bellard.org/nncp/nncp-2023-10-21.tar.gz -O nncp.tar
      - name: Extract NNCP source
        run: tar xf nncp.tar
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential zlib1g-dev
      - name: Build
        run: make -C nncp-2023-10-21
      - uses: actions/upload-artifact@v4
        with:
          name: nncp-linux-to-linux
          path: nncp-2023-10-21/nncp

  build_windows_on_windows:
    needs: generate_version_number
    runs-on: windows-latest
    steps:
      - name: Download NNCP source
        run: Invoke-WebRequest -Uri https://bellard.org/nncp/nncp-2023-10-21.tar.gz -OutFile nncp.tar
        shell: powershell
      - name: Extract NNCP source
        run: tar xf nncp.tar
        shell: bash
      - name: Setup MinGW-w64
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-zlib
          path-type: inherit
      - name: Build with CONFIG_WIN32
        run: |
          echo "CONFIG_WIN32=y" > config.mak
          make -C nncp-2023-10-21
        shell: msys2 {0}
      - uses: actions/upload-artifact@v4
        with:
          name: nncp-windows-to-windows
          path: nncp-2023-10-21/nncp.exe

  build_windows_on_linux:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make

      - name: Download NNCP source
        run: wget https://bellard.org/nncp/nncp-2023-10-21.tar.gz -O nncp.tar

      - name: Extract NNCP source
        run: tar xf nncp.tar

      - name: Build Windows executable on Linux
        run: |
          cd nncp-2023-10-21
          make CC=x86_64-w64-mingw32-gcc LDFLAGS=-static -lz

      - uses: actions/upload-artifact@v4
        with:
          name: nncp-linux-to-windows
          path: nncp-2023-10-21/nncp.exe


  release_github:
    needs: [
      generate_version_number,
      build_windows_on_windows,
      build_linux,
      build_windows_on_linux,
    ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.${{needs.generate_version_number.outputs.build_number}}
          release_name: Release 1.0.${{needs.generate_version_number.outputs.build_number}}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/nncp-linux-to-linux
            ./artifacts/nncp-windows-to-windows
            ./artifacts/nncp-linux-to-windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
